import { NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'
import { GuidesEntry } from '../../components/guides/GuidesEntry'
import { SimpleGrid } from '@mantine/core'
import { GridGuides } from '../../components/grid/GridGuides'

const Guides: NextPage = () => {
    return (
        <Fragment>
            <Head>
                <title>{'Baza danych MGW | Spis poradników'}</title>
                <meta name={'description'} content={'Generated by create next app'} />
            </Head>
            <GuidesEntry />
            <GridGuides>
                <div>{'1'}</div>
                <div>{'2'}</div>
                <div>{'3'}</div>
                <div>{'4'}</div>
            </GridGuides>
        </Fragment>
    )
}

export default Guides
