import { NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'
import { GuidesEntry } from '../../components/guides/GuidesEntry'

const Guides: NextPage = () => {
    return (
        <Fragment>
            <Head>
                <title>{'Baza danych MGW | Spis poradników'}</title>
                <meta name={'description'} content={'Generated by create next app'} />
            </Head>
            <GuidesEntry />
        </Fragment>
    )
}

export default Guides
