import { Fragment } from 'react'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { IChaptersPageProps } from '../../../utils/interfaces/IChapters'
import { TRestChapters, TRestChaptersData } from '../../../utils/types/TChapters'
import { useRouter } from 'next/router'
import { useGetChapter } from '../../../utils/hooks/useGetChapter'
import { IGetChapterProps } from '../../../utils/interfaces/IGetChapter'
import { Tooltip } from '@mantine/core'

const Chapter: NextPage<IChaptersPageProps> = ({ chapters }) => {
    const router = useRouter()
    const getChapterHookData: IGetChapterProps = {
        chapters: chapters,
        chapterId: router.query,
    }
    const { chapter } = useGetChapter(getChapterHookData)

    if (!chapter) router.push('/404')

    return (
        <Fragment>
            <Head>
                <title>{`Baza danych MGW | Spis poradników - ${chapter?.title}`}</title>
                <meta name={'description'} content={'Generated by create next app'} />
            </Head>
            <h2>{chapter?.title}</h2>
            <ul>
                {chapter?.episodes.map((item, index) => (
                    <li key={item.id}>
                        <Tooltip label={item.title} position={'right'} placement={'center'} withArrow wrapLines width={350}>
                            <Link href={item.link}>{item.name}</Link>
                        </Tooltip>
                    </li>
                ))}
            </ul>
        </Fragment>
    )
}

export default Chapter

export const getServerSideProps: GetServerSideProps = async (context) => {
    const response: Response = await fetch('http://localhost:3000/api/chapters', {
        credentials: 'include',
    })
    const chapters: TRestChapters = await response.json()

    return {
        props: {
            chapters,
        },
    }
}
