import type { NextPage } from 'next'
import Head from 'next/head'
import { Fragment, useState } from 'react'
import { AppShell, Burger, Header, MediaQuery, Navbar, Text, useMantineTheme } from '@mantine/core'
import { AppHeader } from '../components/header/Header'

const Home: NextPage = () => {
    const [opened, setOpened] = useState(false)

    return (
        <Fragment>
            <Head>
                <title>{'Baza danych MGW | Strona Główna'}</title>
                <meta name={'description'} content={'Generated by create next app'} />
                <link rel={'icon'} href={'/favicon.ico'} />
            </Head>
            <AppShell
                navbarOffsetBreakpoint={'sm'}
                fixed
                navbar={
                    <Navbar padding={'md'} hiddenBreakpoint={'sm'} hidden={false} width={{ sm: 300, lg: 400 }}>
                        <Text>{'Application navbar'}</Text>
                    </Navbar>
                }
                header={<AppHeader />}
            >
                <Text>{'Test'}</Text>
            </AppShell>
        </Fragment>
    )
}

export default Home
