import type { NextPage } from 'next'
import Head from 'next/head'
import { Fragment, useContext } from 'react'

const Home: NextPage = () => {
    return (
        <Fragment>
            <Head>
                <title>{'Baza danych MGW | Strona Główna'}</title>
                <meta name={'description'} content={'Generated by create next app'} />
            </Head>
            <p>{'strona główna'}</p>
        </Fragment>
    )
}

export default Home
